# Generated by Django 4.2.27 on 2026-02-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Обрабатывается'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен')], default='processing', max_length=20),
        ),
    ]
